'use strict';

let list = [
  { id:128, name: '姚谨'},
  { id:128, name: '孙鹏博'},
  { id:127, name: '简国文'},
  { id:126, name: '李若愚'},
  { id:125, name: '简国文'},
  { id:124, name: '杨川宝'},
  { id:123, name: '喻伟'},
  { id:122, name: '蔡丽'},
  { id:121, name: '梁小军'},
  { id:120, name: '梁小军'},
  { id:119, name: '胡文'},
  { id:118, name: '孙峰'},
  { id:117, name: '张伟杰'},
  { id:116, name: '娄聪'},
  { id:115, name: '杨明军'},
  { id:114, name: '陈晓光'},
  { id:113, name: '汪飞'},
  { id:112, name: '江波'},
  { id:111, name: '付强'},
  { id:110, name: '江波'},
  { id:109, name: '温兴长'},
  { id:108, name: '华林'},
  { id:107, name: '许文'},
  { id:106, name: '邹雄霖'},
  { id:105, name: '程向前'},
  { id:104, name: '任建田'},
  { id:103, name: '程诚'},
  { id:102, name: '齐庆江'},
  { id:101, name: '覃宇辉'},
  { id:100, name: '徐喆'},
  { id:99, name: '林诚'},
  { id:98, name: '李波'},
  { id:97, name: '闫立'},
  { id:96, name: '王诗景'},
  { id:95, name: 'Cotton\' H.'},
  { id:94, name: '陈果'},
  { id:93, name: '李可'},
  { id:92, name: '马跃锋'},
  { id:91, name: '万重阳'},
  { id:90, name: '彭亮'},
  { id:89, name: '张炳臣'},
  { id:88, name: '莫强龙'},
  { id:87, name: '王飞'},
  { id:86, name: '金晨'},
  { id:85, name: '薛晶义'},
  { id:84, name: '苏秦'},
  { id:83, name: '周中原'},
  { id:82, name: '丁全'},
  { id:81, name: '田霖'},
  { id:80, name: '魏磊哲'},
  { id:79, name: '池海跃'},
  { id:78, name: '魏娥'},
  { id:77, name: '李胜'},
  { id:76, name: '张雷'},
  { id:75, name: '姚永君'},
  { id:74, name: '薛梦飞'},
  { id:73, name: '师小强'},
  { id:72, name: '陈雨佳'},
  { id:71, name: '李耀力'},
  { id:70, name: '朱鹏飞'},
  { id:69, name: '王俊星'},
  { id:68, name: '王小飞'},
  { id:67, name: 'Lever'},
  { id:66, name: '李红军'},
  { id:65, name: '赵玉勇'},
  { id:64, name: '闫宇帅'},
  { id:63, name: '唐建峰'},
  { id:62, name: '陈海舟'},
  { id:61, name: '李晓倩'},
  { id:60, name: '孙斌'},
  { id:59, name: '杜晓卿'},
  { id:58, name: '刘奎'},
  { id:57, name: '闫萌'},
  { id:56, name: '朝沐金风'},
  { id:55, name: 'Luana.D'},
  { id:54, name: '张健亮'},
  { id:53, name: '余玲'},
  { id:52, name: 'stella'},
  { id:51, name: '李倩'},
  { id:50, name: '颜景豪'},
  { id:49, name: '王尧'},
  { id:48, name: '李华龙'},
  { id:47, name: '哥特复兴'},
  { id:46, name: '徐佳栋'},
  { id:45, name: '王会'},
  { id:44, name: '郑召召'},
  { id:43, name: '沈倩囡'},
  { id:42, name: '张楚隽'},
  { id:41, name: '林瑜'},
  { id:40, name: '胡俊'},
  { id:39, name: '李琳'},
  { id:38, name: '李榜'},
  { id:37, name: '巫荣'},
  { id:36, name: 'Felix'},
  { id:35, name: '张宗正'},
  { id:34, name: '刘奎'},
  { id:33, name: '夏国英'},
  { id:32, name: '罗冉'},
  { id:31, name: '史啸'},
  { id:30, name: '易成波'},
  { id:29, name: '胡鹏飞'},
  { id:28, name: '张弛'},
  { id:27, name: '李天元'},
  { id:26, name: '丁坚'},
  { id:25, name: '朱羽明'},
  { id:24, name: '赵鹏程'},
  { id:23, name: '吴杰'},
  { id:22, name: '尚彬彬'},
  { id:21, name: '王凯'},
  { id:20, name: '青蛙'},
  { id:19, name: '李志玮'},
  { id:18, name: '周林'},
  { id:17, name: '夏蕾'},
  { id:16, name: '苗宇佳'},
  { id:15, name: 'leslie'},
  { id:14, name: '黄泰钊'},
  { id:13, name: '张华'},
  { id:12, name: '金麒麟'},
  { id:11, name: '沈桂姗'},
  { id:10, name: '王朋'},
  { id:9, name: '陈波'},
  { id:8, name: '杨洁'},
  { id:7, name: '王小三'},
  { id:6, name: 'iu2fish'},
  { id:5, name: '米粽'},
  { id:4, name: '王庆磊'},
  { id:3, name: '陈林泳'},
  { id:2, name: '杨骁伟'},
  { id:1, name: '奇昊'},
];

function rand(min, max) {
  if (max == null) {
    max = min;
    min = 0;
  }
  return min + Math.floor(Math.random() * (max - min + 1));
};

var res = [];

for (var i = 0; i < 60; i++) {
  var index = rand(0, list.length - 1);
  res.push(list[index]);
  list.splice(index, 1);
}

console.log('res', res);
